import React from "react";
import "./TermsConditions.css";


const TermsConditions = () => {
    return (
        <section className="terms-conditions">
            <h2 className="terms-header">TERMS & CONDITIONS</h2>
            <ul className='terms-conditions-list'>
                <li className='terms-conditions-list-item privacy-sub-header'>Nifty10</li>
                <p className='privacy-text'>Finpages tech private limited operates the portal in India, which offers fantasy stock trading games through the web-portal Nifty10 and website(s) and mobile application(s) (collectively referred to as the “Portal”) (Finpages tech private limited referred to herein as “Nifty10” or “we” or “us” “our”)</p>
                <li className='terms-conditions-list-item privacy-sub-header'>Definitions and Interpretation</li>
                <p className='privacy-text'>The following terminology applies to these Terms and Conditions, unless the context requires otherwise: “User” “you” and “your” refers to, any person that uses, accesses, links to, or refers to the Portfolio or Nifty10.</p>
                <p className='privacy-text'>Certain Services provided on the Portal may be subject to additional rules, terms and conditions. To the extent these Terms and Conditions are inconsistent with the additional conditions set down, the additional conditions shall prevail.</p>
                <li className='terms-conditions-list-item privacy-sub-header'>Game of Skill</li>
                <p className='privacy-text'>Games of skill are legal, as they are excluded from the ambit of Indian gambling legislations including, the Public Gambling Act of 1867.The Indian Supreme Court in the cases of State of Andhra Pradesh v. K Satyanarayana (AIR 1968 SC 825) and KR Lakshmanan v. State of Tamil Nadu (AIR 1996 SC 1153) has held that a game in which success depends predominantly upon the superior knowledge, training, attention, experience and adroitness of the player shall be classified as a game of skill.</p>
                <p className='privacy-text'>The Games are games of skill as success of Users depends primarily on their superior knowledge of the mechanics of the stock market, knowledge of a company’s performance, understanding of key financial concepts, judgment, strategy and multi-disciplinary knowledge, training, calculation and mathematics, attention and dedication towards the Game(s) and adroitness in playing the Game(s). The Game(s) also requires Users to create well-balanced Baskets with limited resources and appointment of appropriate securities as superstar stock and star stock to gain the maximum points.</p>
                <p className='privacy-text'>The value of the prize money awarded to winners does not correlate to the value of the actual stocks in the stock market, and neither the fantasy stocks nor the Baskets amount to ‘securities’ or ‘derivatives’ under Indian law and therefore the Games are purely fantasy games which require skills to be applied by the User.</p>
                <p className='privacy-text'>By participating in the Game(s), each User acknowledges and agrees that he/she is participating in a game of skill.</p>
                <li className='terms-conditions-list-item privacy-sub-header'>Usage of the Portal</li>
                <p className='privacy-text'>These terms and conditions regulate your use of the Portal, and form a binding legal contract between Finpages tech private limited (the owner and operator of the Portal) and you. By accessing the Portal, you hereby accept these Terms and Conditions, Privacy Policy and any other disclaimers or terms made available on the Portal as may be amended from time to time. Do not continue to use the Portal if you do not agree to all of such Terms and Conditions, Privacy Policy and disclaimers and terms on the Portal.</p>
                <p className='privacy-text'>Nifty10 reserves the right to modify these Terms and Conditions, Privacy Policy, disclaimers and terms related to the services, contests and games we provide (“Game” or “Services”) at its sole discretion.</p>
                <p className='privacy-text'>Publication of any updated / amended Terms and Conditions, Privacy Policy, disclaimers and terms related to Services on the Portal shall be deemed to be sufficient notification of the changes or modifications to the Terms and Conditions, Privacy Policy, disclaimers and terms related to the Services, to the User. The continued use of the Portal by a User subsequent to modification / change in the Terms and Conditions, Privacy Policy, disclaimers and terms related to the Services, constitutes the User’s acceptance to the modified / changed Terms and Conditions, Privacy Policy, disclaimers and terms related to the Services.</p>
                <p className='privacy-text'>Notwithstanding the above, Nifty10 may, at its sole discretion, also notify the User of any change or modification in these Terms and Conditions, rules, regulations and terms of use referred to herein or provided by Nifty10, by way of sending an email to the User’s registered email address or posting notifications in the User accounts. The User may then exercise the options provided in such an email or notification to indicate non-acceptance of the modified Terms and Conditions, rules, regulations and terms of use referred to herein or provided by Nifty10. If such options are not exercised by the User within the time frame prescribed in the email or notification, the User will be deemed to have accepted the modified Terms and Conditions, rules, regulations and terms of use referred to herein or provided by Nifty10.</p>
                <li className='terms-conditions-list-item privacy-sub-header'>Eligibility</li>
                <p className='privacy-text'>A User must register on the Portal to access the Services and participate in Games provided on the Portal.</p>
                <p className='privacy-text'>To access Games(s) on the Portal a User must be (a) 18 (eighteen) years of age or older at the time of registration; and (b) a resident of India.</p>
                <p className='privacy-text'>Nifty10 may, at its sole discretion, prescribe additional eligibility criteria with respect to specific Games (“Additional Eligibility Criteria”), and Users shall be allowed to participate in such Games subject to satisfaction of the eligibility criteria provided therein.</p>
                <p className='privacy-text'>A User’s access to Services on the Portal may be restricted by Nifty10 at any time, in its sole discretion.</p>
                <p className='privacy-text'>REGISTRATION OF ANY USER ON THE PORTAL IS VOID WHERE IT IS RESTRICTED OR PROHIBITED BY LAW.</p>
                <li className='terms-conditions-list-item privacy-sub-header'>Registration on the Portal</li>
                <p className='privacy-text'>In order to avail any of the Services through the Portal, the User is required to register on the Portal, which may involve without limitation, setting up of a profile, username and password. The User will be solely responsible to ensure confidentiality of his/her username or passwords or account on the Portal.</p>
                <p className='privacy-text'>In order to register on the Portal, the Users are required to accurately provide the following information:</p>
                <ul className='privacy--list'>
                    <li className='privacy-list-item'>Name</li>
                    <li className='privacy-list-item'>Email address</li>
                    <li className='privacy-list-item'>Password</li>
                    <li className='privacy-list-item'>State of residence</li>
                    <li className='privacy-list-item'>Date of Birth</li>
                    <li className='privacy-list-item'>Gender</li>
                </ul>
                <p className='privacy-text'>Users are also required to confirm that they have read and shall abide by these Terms and Conditions.</p>
                <p className='privacy-text'>If a User chooses a username that, Nifty10 considers in his opinion that is obscene, indecent, abusive or that might subject Nifty10 to public disparagement or scorn, or a name which is a name of any celebrity, brand, business house, as the case may be, Nifty10 reserves the right, without prior notice to the User, to:</p>
                <ol className="terms-conditions-sub-list decimal-sub-list">
                    <li className='privacy-text'>restrict usage of such names, which in Nifty10’s opinion falls within any of the said categories; and/or</li>
                    <li className='privacy-text'>change such username and intimate the User; and/or</li>
                    <li className='privacy-text'>delete such username and deny such User to access the Portal.</li>
                </ol>
                <p className='privacy-text'>By registering, the User hereby grants consent for contacting via telephone or email based on the information furnished by the user either by us, or our affiliates or third parties nominated in this regard for providing better services or for promotional activities related to the Services.</p>
                <p className='privacy-text'>The User agrees and covenants that:</p>
                <ol className="terms-conditions-sub-list decimal-sub-list">
                    <li className="privacy-text">
                        The basic information, personally identifiable information, provided by him/her are true, complete and accurate, and the user agrees not to submit any particulars which are false or any information to which he/she does not have any right or authority to provide; and
                    </li>
                    <li className="privacy-text">
                        The User shall not register or operate more than one User account for accessing the Portal or accessing the Services.
                    </li>
                </ol>

                <li className='terms-conditions-list-item privacy-sub-header'>Participation in Game(s)</li>
                <p className='privacy-text'>All Users that are registered and logged in to their accounts on the Portal shall be eligible to participate in the Game(s), subject to compliance with the eligibility criteria set out in Clause 5 hereinabove.</p>
                <li className='terms-conditions-list-item privacy-sub-header'>Conditions of Participation</li>
                <p className='privacy-text'>By entering a Game, the User agrees to be bound by these Terms and Conditions and the decisions of Nifty10, which are made in Nifty10’s sole discretion and are final and binding in all matters related to the Game. Subject to the terms and conditions stipulated herein below, Nifty10, at its sole discretion, may disqualify any user from a Game, void all account balances, refuse to award benefits or prizes and require the return of any prizes, if the user engages in unfair conduct, which Nifty10 deems to be improper, unfair or otherwise adverse to the operation of the Game or is in any way detrimental to other Users which includes, but is not limited to:</p>
                <ol className="terms-conditions-sub-list decimal-sub-list">
                    <li className="privacy-text">Falsifying one's own personal information (including, but not limited to, name, email address, bank account details and/or any other information or documentation as may be requested by Nifty10 to enter a Game and/or claim a prize/winning);</li>
                    <li className="privacy-text">Engaging in any type of financial fraud or misrepresentation including unauthorized use of credit/debit instruments, payment wallet accounts etc. to enter a Game or claim a prize. It is expressly clarified that the onus to prove otherwise shall solely lie on the user;</li>
                    <li className="privacy-text">Colluding with any other user(s) or engaging in any type of syndicate play;</li>
                    <li className="privacy-text">Any violation of Game rules or the Terms of Use;</li>
                    <li className="privacy-text">Accumulating points or prizes through unauthorized methods such as automated bots, or other automated means;</li>
                    <li className="privacy-text">Using automated means (including but not limited to harvesting bots, robots, parser, spiders or screen scrapers) to obtain, collect or access any information on the Portal or of any User for any purpose;</li>
                    <li className="privacy-text">Any type of misuse of any offers or promotions;</li>
                    <li className="privacy-text">Tampering with the administration of a Game or trying to in any way tamper with the computer programs or any security measure associated with a Game;</li>
                    <li className="privacy-text">Obtaining other users’ information without their express consent and/or knowledge and/or spamming other users (Spamming may include but shall not be limited to sending unsolicited emails to users, sending bulk emails to Nifty10 Users, sending unwarranted email content either to selected Users or in bulk);</li>
                    <li className="privacy-text">Abusing through the Portal in any way (‘unparliamentary language, slangs or disrespectful words’ are some of the examples of abuse);</li>
                    <li className="privacy-text">Using proceeds of crime for the purposes of making any payments on the Portal;</li>
                    <li className="privacy-text">Instituting, assisting or becoming involved in any type of attack, including without limitation, distribution of a virus, denial of service, or other attempts to disrupt the Portal, Services or any other person’s use or enjoyment of the Services;</li>
                    <li className="privacy-text">To transmit files that contain viruses, corrupted files, or any other similar software or programs that may damage or adversely affect the operation of another User’s computer, mobile, device, Portal, or any software, hardware, or telecommunications equipment;</li>
                    <li className="privacy-text">To advertise, offer or sell any goods or services for any commercial purpose on Portal without express written consent of Nifty10;</li>
                    <li className="privacy-text">To collect or store personal information about other Users; or</li>
                    <li className="privacy-text">To use the Services in violation of any extant laws, including but not limited to laws and regulations promulgated by the Securities and Exchange Board of India.</li>
                </ol>

                <p className='privacy-text'>It is clarified that in case a User is found to be in violation of these Terms and Conditions, Nifty10 reserves its right to initiate appropriate civil/criminal remedies as it may be advised other than forfeiture and/or recovery of prize money if any.</p>
                <p className='privacy-text'>Unauthorized access to Portal is a breach of these Terms and Conditions, and a violation of the law. Users agree not to access the Portal by any means other than through the interface that is provided by Portal for use in accessing the Services. Users agree not to use any automated means, including, without limitation, agents, robots, scripts, or spiders, to access, monitor, or copy any part of our sites except those automated means that Nifty10 has approved in advance.
                    Nifty10 reserves the right to move entrants from the Game(s) they have entered to substantially similar Game(s) in certain situations determined by Nifty10 in its sole discretion.</p>
                <li className='terms-conditions-list-item privacy-sub-header'>User Conduct</li>
                <p className='privacy-text'>Users agree to abide by these Terms and Conditions and all other rules, regulations and terms of use of the Portal. In the event User does not abide by these Terms and Conditions and all other rules, regulations and terms of use, Nifty10 may, at its sole and absolute discretion, take necessary remedial action, including but not limited to:
                    restricting, suspending, or terminating any User’s access to all or any part of the Services;
                    deactivating or deleting a User’s account and all related information and files on the account. Any amount remaining unused in the User’s ‘Amount Unutilized account’ or Winnings Account (subject to deduction of applicable TDS with effect from 1st April 2023 as applicable) on the date of deactivation or deletion shall be transferred to the User’s bank account on record with Nifty10 subject to a processing fee (if any) applicable on such transfers as set out herein; or
                    refraining from awarding any prize(s) to such User.
                    Users shall not register or operate more than one User account with Nifty10.</p>
                <p className='privacy-text'>Users agree to provide true, accurate, current and complete information at the time of registration and at all other times (as required by Nifty10). Users further agree to update and keep updated their registration information.
                    Users agree to ensure that they can receive all communication from Nifty10 by marking e-mails or sending SMSs from Nifty10 as part of their “safe senders” list. Nifty10 shall not be held liable if any e-mail/SMS remains unread by a User as a result of such e-mail getting delivered to the User’s junk or spam folder.</p>
                <p className='privacy-text'>Any password issued by Nifty10 to a User may not be revealed to anyone else. Users may not use anyone else’s password. Users are responsible for maintaining the confidentiality of their accounts and passwords. Users agree to immediately notify Nifty10 of any unauthorized use of their passwords or accounts or any other breach of security.
                    Users agree to exit/log-out of their accounts at the end of each session. Nifty10 shall not be responsible for any loss or damage that may result if the User fails to comply with these requirements.
                    Users agree not to use cheats, exploits, automation, software, bots, hacks or any unauthorized third party software designed to modify or interfere with Nifty10 Services and/or Nifty10 experience or assist in such activity.
                    Users agree not to copy, modify, rent, lease, loan, sell, assign, distribute, reverse engineer, grant a security interest in, or otherwise transfer any right to the technology or software underlying the Portal or the Services.</p>
                <p className='privacy-text'>Users agree that without Nifty10’s express written consent, they shall not modify or cause to be modified any files or software that are part of the Services.
                    Users agree not to disrupt, overburden, or aid or assist in the disruption or overburdening of (a) any computer or server used to offer or support the Portal or the Services (each a “Server“); or (b) the enjoyment of the Services by any other User or person.
                    Users agree not to institute, assist or become involved in any type of attack, including without limitation to distribution of a virus, denial of service, or other attempts to disrupt the Services or the Portal or any other person’s use or enjoyment of the Services or the Portal.</p>
                <p className='privacy-text'>Users shall not attempt to gain unauthorized access to the User accounts, Servers or networks connected to the Services or the Portal by any means other than the User interface provided by Nifty10, including but not limited to, by circumventing or modifying, attempting to circumvent or modify, or encouraging or assisting any other person to circumvent or modify, any security, technology, device, or software that underlies or is part of the Portal or the Services.
                    User shall not to publish any content that is patently false and untrue, and is written or published in any form, with the intent to mislead or harass a person, entity or agency for financial gain or to cause any injury to any person.Without limiting the foregoing, Users agree not to use Nifty10 for any of the following:</p>
                <p className='privacy-text'>Use of the Portal is subject to existing laws and legal processes. Nothing contained in these Terms and Conditions shall limit Nifty10’s right to comply with governmental, court, and law-enforcement requests or requirements relating to Users’ use of Nifty10.
                    Users may reach out to Nifty10 through Helpdesk if the user has any concerns with regard to a match and/or contest within Forty Eight (48) hours of winner declaration for the concerned contest.
                    Nifty10 may not be held responsible for any content contributed by Users on the Portal.</p>
                <li className='terms-conditions-list-item privacy-sub-header'>Games</li>
                <p className='privacy-text'>As part of the Games, Nifty10 may make fantasy stock trading contests available on its Portal. Users wishing to participate in such Games are invited to create their own basket of securities consisting of real life securities listed on recognized Indian stock exchanges. Nifty10 offers its Portal to Users for fantasy Games being created in relation to the securities market, and the Users can participate in such Game(s) with their basket of fantasy securities (“Basket”).</p>
                <p className='privacy-text'>Nifty10 reserves the right to abandon a specific round or adjust the deadline of a round in a Game in certain specific, uncertain scenarios, which are beyond Nifty10’s reasonable control.</p>
                <p className='privacy-text'>Baskets are awarded points based on the performance of the real life securities on the stock exchanges at the end of a designated Game or round in a Game.
                    The Games across the Portal, in addition to the Terms and Conditions, shall be governed by the rules available at How to Play – Fantasy Stock Trading, and other rules and regulations published on the page of the relevant Game, and all Users participating in a Game agree to abide by such rules and regulations, as applicable.</p>
                <p className='privacy-text'>Nifty10 may make available on its Portal paid versions of certain Games (“Paid Games”). Users may participate in Paid Games by paying the pre-designated amount as provided on the relevant Paid Game’s page. The Participant with the highest aggregate points at the end of the pre-determined match shall be eligible to win a pre-designated prize which is disbursed out of prize money pool, as stated on the relevant Contest(s) page.</p>
                <p className='privacy-text'>Users participating Paid Games hereby authorize Nifty10 to appoint a third party to manage user funds on users behalf.</p>
                <li className='terms-conditions-list-item privacy-sub-header'>Payment Terms- Withdrawls, Refunds & Cancellation</li>
                <p className='privacy-text'>By inputting a payment method, the User hereby affirms that the User is the lawful owner of the payment method account used to make any deposit(s) on the Portal. It shall be a violation of these Terms and Conditions for any User to submit payment using any payment method that is not owned by the User.</p>
                <p className='privacy-text'>In respect of any transactions entered into on the Nifty10 Portal, including making a payment to participate in the Paid Games, Users agree to be bound by the following payment terms:</p>
                <ol className="terms-conditions-sub-list decimal-sub-list">
                    <li className='privacy-text'>The payment of pre-designated amount Users make to participate in the Paid Game(s) is inclusive of the pre-designated Portal fee for access to the Nifty10 Services charged by Nifty10 and pre-determined participant’s contribution towards prize money pool.</li>
                    <li className='privacy-text'>Subject to these Terms and Conditions, all amounts collected from the User are held in a separate non-interest earning bank accounts. The said accounts are operated by a third party appointed by Nifty10 in accordance with Clause 10 of these Terms and Conditions. From these bank accounts, the payouts can be made to (a) Users (towards their withdrawals), (b) Nifty10 (towards its Portal Fees) and to (c) Government (towards GST payable), and to (d) Government (towards TDS on winnings amount).</li>
                    <li className='privacy-text'>Nifty10 reserves the right to charge a Portal fee, which would be specified and notified by Nifty10 on the Contest page, being created on the Portal, prior to a User’s joining of such Contest. The Portal Fee will be debited from the User’s account balance.</li>
                    <li className='privacy-text'>From 01 Oct 2023, 28% GST is applicable on amount deposited by the User in its ‘Amount Unutilized’ account with Nifty10 platform. User can view the GST paid on each deposit through invoices on ‘My Transaction’ page.</li>
                    <li className='privacy-text'>The User may participate in Paid Game wherein the User has to contribute a pre-specified contribution towards the prize money pool of such Paid Game, which will be passed on to the winner(s) of the Game after the completion of the Contest as per the terms and conditions of such Contest. It is clarified that Nifty10 has no right or interest in this prize money pool, and only acts as an intermediary engaged in collecting and distributing the prize money pool in accordance with the terms and conditions of the Paid Game. The amount to be paid-in by the User towards the prize money pool would also be debited from the User’s account balance maintained with the third party..</li>
                    <li className='privacy-text'>Any User availing Nifty10 services are provided with two categories of accounts for the processing and reconciliation of payments: (i) ‘Amount Unutilized’ Account, (ii) Winnings Account. It is clarified that transfer of any amounts in the User’s accounts to any other category of account held by the user or any third party account, including a bank account held by a third party is not permitted:</li>
                    <ol className="terms-conditions-sub-list roman-sub-list">
                        <li className='privacy-text'>User’s winnings in any Contest will reflect as credits to the User’s Winnings Account.</li>
                        <li className='privacy-text'>User’s remitting the amount through the designated payment gateway shall be credited to User’s Amount Unutilized’ Account.</li>
                    </ol>
                    <li className='privacy-text'>Each time a User participates in any Paid Game on the Portal, the pre-designated amount shall be debited from the User’s account. In debiting amounts from the User’s accounts towards the pre-designated amount of such user shall be debited from the User’s ‘Amount Unutilized’ Account and thereafter, any remaining amount of participation fee shall be debited from the User’s Winning Account.</li>
                    <li className='privacy-text'>In case there is any amount remaining to be paid by the User in relation to such User’s participation in any Paid Game(s), the User will be taken to the designated payment gateway to give effect to such payment. At the time of making the deposit, the User agrees that Nifty10 will collect applicable Government Taxes (such as GST @ 28%) in addition to the amount to be deposited by the User in its ‘Amount Unutilized’ Account. This will be duly reflected by Nifty10 to the User at the time of making payment. In case any amount added by the User exclusive of applicable Government Taxes (such as GST @ 28%) through such payment gateway exceeds the remaining amount of the pre-designated amount, the amount in excess shall be transferred to the User’s ‘Amount Unutilized’ Account and will be available for use in participation in any Paid Game(s).</li>
                    <li className='privacy-text'>Debits from the ‘Amount Unutilized’ Account for the purpose of enabling a User’s participation in a Paid Game shall be made in order of the date of credit of amounts in the ‘Amount Unutilized’ Account, and accordingly amounts credited into ‘Amount Unutilized’ Account earlier in time shall be debited first.</li>
                    <li className='privacy-text'>All amounts credited into a User’s ‘Amount Unutilized’ Account must be utilized within 335 (three hundred and thirty five) days of credit. In case any unutilized amount lies in the ‘Amount Unutilized’ Account after the completion of 335 (three hundred and thirty five) days from the date of credit of such amount, Nifty10 reserves the right to forfeit such unutilized amount, without liability or obligation to pay any compensation to the User.</li>
                    <li className='privacy-text'>Withdrawal of any amount standing to the User’s credit in the Winnings Account may be made by way of a request to Nifty10. Nifty10 shall effect an online transfer to the User’s bank account on record with Nifty10 within a commercially reasonable period of time. Such transfer will reflect as a debit to the User’s Winnings Account. Nifty10 shall not charge any processing fee for the online transfer of such amount from the Winnings Account to the User’s bank account on record with Nifty10. Users are requested to note that they will be required to provide valid photo identification, PAN Card and address proof documents for proof of identity and address in order for Nifty10 to process the withdrawal request. The name mentioned on the User’s photo identification document should correspond with the name provided by the User at the time of registration on Nifty10, as well as the name and address existing in the records of the User’s bank account as provided to Nifty10. In the event that no bank account has been registered by the User against such User’s account with Nifty10, or the User has not verified his/her User account with Nifty10, to Nifty10’s satisfaction and in accordance with these Terms and Conditions, and in case the User fails to register a bank account with his/her User account and/or to verify his/her User account, Nifty10 shall not transfer any Winning amounts to the User.</li>
                    <li className='privacy-text'>Users agree that once they confirm a transaction on Nifty10, they shall be bound by and make payment for that transaction.</li>
                    <li className='privacy-text'>The User acknowledges that subject to time taken for bank reconciliations and such other external dependencies that Nifty10 has on third parties, any transactions on the Portal may take up to 24 hours to be processed. Any amount paid or transferred into the User’s ‘Amount Unutilized’ Account or Winnings Account may take up to 24 hours to reflect in the User’s ‘Amount Unutilized’ Account or Winnings Account balance. Similarly, the utilization of the discount points or discount bonus or money debited from ‘Amount Unutilized’ Account or Winnings Account may take up to 24 hours to reflect in the User’s ‘Amount Unutilized’ Account or Winnings Account balance. Users agree not to raise any complaint or claim against Nifty10 in respect of any delay, including any lost opportunity to join any Paid Game due to delay in crediting of transaction amount into any of the User’s accounts. A transaction, once confirmed, is final and no cancellation is permissible.</li>
                    <li className='privacy-text'>Nifty10 may, in certain exceptional circumstances and at its sole and absolute discretion, refund the amount to the User after deducting applicable cancellation charges and taxes. Any refunds issued by Nifty10 shall be processed within a period seven (7) to ten (10) working days from the date of initiation of such refund. At the time of the transaction, Users may also be required to take note of certain additional terms and conditions and such additional terms and conditions shall also govern the transaction. To the extent that the additional terms and conditions contain any clause that is conflicting with the present terms and conditions, the additional terms and conditions shall prevail.</li>
                </ol>
                <li className='terms-conditions-list-item privacy-sub-header'>Discounts Offered</li>
                <p className='privacy-text'>In order to conduct promotional activities and provide incentives, Nifty10 may gratuitously issue discounts to the User which may be utilized for any Paid Game(s) and no User shall be permitted to transfer or request the transfer of any amount of discounts to any other account. The usage of any discounts issued as a promotional measure or to provide incentives shall be subject to the limitations and restrictions, including without limitation, restrictions as to time within which discounts must be used, as applied by Nifty10 and notified to the User at the time of issue of such amount. The issue of any discounts to the Users is subject to the sole discretion of Nifty10 and cannot be demanded by any User as a matter of right. The issue of any discount by Nifty10 on any day shall not entitle the User to demand the issuance of such discount at any subsequent period in time nor create an expectation of recurring issue of such discount by Nifty10 to such User. The discount granted to the User may be used by such User for the purpose of setting off against the contribution to prize pool in any Paid Game, in accordance with these Terms and Conditions. The discounts shall not be withdraw-able or transferrable to any other account of the User, including the bank account of such User, or of any other User or person, other that as part of the winnings of a User in any Paid Game(s) In case the User terminates his/her account with Nifty10 or such account if terminated by Nifty10, all discounts granted to the user shall return to Nifty10 and the User shall not have any right or interest on such discount.Nifty10 currently grants discounts of three types :</p>
                <ol className="terms-conditions-sub-list decimal-sub-list">
                    <li className='privacy-text'>Discount Bonus:</li>
                    <ol className="terms-conditions-sub-list roman-sub-list">
                        <li className='privacy-text'>All Discount Bonus awarded in the User account shall be valid for a period of 14 days from the date of award. The Discount Bonus shall lapse at the end of 14 days.</li>
                        <li className='privacy-text'>The Discount Bonus amount shall reflect in a separate “Discount Bonus” account.</li>
                        <li className='privacy-text'>Discount bonus is non-transferable and cannot be withdrawn.</li>

                    </ol>
                    <li className='privacy-text'>Discount Points:</li>
                    <ol className="terms-conditions-sub-list roman-sub-list">
                        <li className='privacy-text'>All Discount Points shall be valid for a period of three (3) months from the date of award of points.</li>
                        <li className='privacy-text'>Discount Points are non-transferable, cannot be withdrawn.</li>
                        <li className='privacy-text'>Discount points are awarded on successful deposit in the ‘Amount Unutilized’ account. In the event of any withdrawal of the deposited amount in ‘Amount Unutilized’ account, the Discount Points given to the user for such deposit amount shall also be captured and the user will not be able to utilize such captured Discount Points.</li>
                        <li className='privacy-text'>Discount Points can be utilized for joining a contest as a discount for a maximum of 22% of the contest entry amount (less any other discounts available with the user).</li>
                        <li className='privacy-text'>In the event of a match abandonment or cancellation, the Discount Points used by the user in such contest shall be returned to the users Discount Points Account.</li>
                    </ol>
                    <li className='privacy-text'>Discount Coupons:</li>
                    <ol className="terms-conditions-sub-list roman-sub-list">
                        <li className='privacy-text'>Discount coupons shall be given by Nifty10 at its sole discretion.</li>
                        <li className='privacy-text'>Each discount coupon shall be governed by the specific terms and conditions as notified by Nifty10 at the time of grant of such discount coupons.</li>
                        <li className='privacy-text'>Each discount coupon shall have its own validity and specific terms and conditions.</li>
                    </ol>
                </ol>
                <p className='privacy-text'>In case of any conflict between these terms and the terms specific to the discount coupon, the terms specific to the discount coupon shall prevail</p>
                <li className='terms-conditions-list-item privacy-sub-header'>Verification of Winners</li>
                <p className='privacy-text'>Winners shall be decided on the basis of the scores of their Baskets in a designated Game. The Users owning the Baskets with the highest aggregate score in a particular Game will be declared as the Winner(s). In certain pre-specified Games, Nifty10 may declare more than one winner and distribute prizes to such winners in increasing order of their Basket’s aggregate score at the end of the designated Game. The contemplated number of winners and the prize due to each winner in such Game shall be as specified on the Game page prior to the commencement of the Game.</p>
                <p className='privacy-text'>Winners shall be contacted by Nifty10 or the third party conducting the Contest on the e-mail address provided at the time of registration. The verification process and the documents required for the collection of prize shall be detailed to the Winners at this stage. As a general practice, winners will be required to provide following documents:</p>
                <ol className="terms-conditions-sub-list decimal-sub-list">
                    <li className='privacy-text'>Photocopy of the User’s PAN card</li>
                    <li className='privacy-text'>Photocopy of a government-issued residence proof</li>
                    <li className='privacy-text'>User’s bank account details and proof of the same</li>
                </ol>
                <p className='privacy-text'>Nifty10 shall not permit a winner to withdraw his/her prize(s)/accumulated winnings unless the above-mentioned documents have been received and verified within the time-period stipulated by Nifty10. The User represents and warrants that the documents provided in the course of the verification process are true copies of the original documents to which they relate.</p>
                <p className='privacy-text'>Users are required to provide proper and complete details at the time of registration. Nifty10 shall not be responsible for communications errors, commissions or omissions including those of the Users due to which the results may not be communicated to the winner.</p>
                <p className='privacy-text'>The list of winners shall be posted on a separate web-page on the Nifty10. The winners will also be intimated by e-mail.</p>
                <p className='privacy-text'>In the event that a User has been declared a winner on the abovementioned web-page but has not received any communication from Nifty10, such User may contact Nifty10 within the time specified on the webpage.</p>
                <p className='privacy-text'>Only those winners who successfully complete the verification process and provide the required documents within the time limit specified by Nifty10 shall be permitted to withdraw/receive their accumulated winnings (or any part thereof). Nifty10 shall not entertain any claims or requests for extension of time for submission of documents.</p>
                <p className='privacy-text'>Nifty10 shall scrutinize all documents submitted and may, at its sole and absolute discretion, disqualify any winner from withdrawing his accumulated winnings (or any part thereof) on the following grounds:</p>
                <ol className="terms-conditions-sub-list roman-sub-list">
                    <li className='privacy-text'>Determination by Nifty10 that any document or information submitted by the User is incorrect, misleading, false, fabricated, incomplete or illegible</li>
                    <li className='privacy-text'>User does not fulfill the eligibility criteria specified in Clause 5 above</li>
                    <li className='privacy-text'>Any other ground.</li>
                </ol>
                <li className='terms-conditions-list-item privacy-sub-header'>Third Party Sites</li>
                <p className='privacy-text'>The Portal may contain links to other Internet sites owned and operated by third parties. Users’ use of each of those sites is subject to the conditions, if any, posted by the sites. Nifty10 does not exercise control over any internet sites apart from the Portal and cannot be held responsible for any content residing in any third-party internet site. Nifty10’s inclusion of third-party content or links to third-party Internet sites is not an endorsement by Nifty10 of such third-party Internet site.</p>
                <p className='privacy-text'>Users’ correspondence, transactions/offers or related activities with third parties, including payment providers and verification service providers, are solely between the User and that third party. Users’ correspondence, transactions and usage of the services/offers of such third party shall be subject to the terms and conditions, policies and other service terms adopted/implemented by such third party, and the User shall be solely responsible for reviewing the same prior to transacting or availing of the services/offers of such third party. User agrees that Nifty10 will not be responsible or liable for any loss or damage of any sort incurred as a result of any such transactions/offers with third parties. Any questions, complaints, or claims related to any third party product or service should be directed to the appropriate vendor.</p>
                <p className='privacy-text'>The Portal contains content that is created by Nifty10 as well as content provided by third parties. Nifty10 does not guarantee the accuracy, integrity, quality of the content provided by third parties and such content may not relied upon by the Users in utilizing the Nifty10 Services provided on Nifty10 including while participating in any of the contests hosted on Nifty10.</p>
                <li className='terms-conditions-list-item privacy-sub-header'>Intellectual Property</li>
                <p className='privacy-text'>The Portal includes a combination of content created by Nifty10, its partners, affiliates, licensors, associates and/or Users. The intellectual property rights (“Intellectual Property Rights“) in all software underlying Nifty10 and the Nifty10 Portal and material published on the Portal, including (but not limited to) Games, software, advertisements, written content, photographs, graphics, images, illustrations, marks, logos, audio or video clippings and flash animation, is owned by Nifty10, its partners, licensors and/or associates. Users may not modify, publish, transmit, participate in the transfer or sale of, reproduce, create derivative works of, distribute, publicly perform, publicly display, or in any way exploit any of the materials or content on Nifty10 either in whole or in part without express written license from Nifty10.</p>
                <p className='privacy-text'>Users may request permission to use any Nifty10 content by writing to Helpdesk.</p>
                <p className='privacy-text'>Users are solely responsible for all materials (whether publicly posted or privately transmitted) that they upload, post, e-mail, transmit, or otherwise make available on the Portal (“Users’ Content“). Each User represents and warrants that he/she owns all Intellectual Property Rights in the User’s Content and that no part of the User’s Content infringes any third party rights. Users further confirm and undertake to not display or use of the names, logos, marks, labels, trademarks, copyrights or intellectual and proprietary rights of any third party on the Portal. Users agree to indemnify and hold harmless Nifty10, its directors, employees, affiliates and assigns against all costs, damages, loss and harm including towards litigation costs and counsel fees, in respect of any third party claims that may be initiated including for infringement of Intellectual Property Rights arising out of such display or use of the names, logos, marks, labels, trademarks, copyrights or intellectual and proprietary rights on the Portal, by such User or through the User’s commissions or omissions.</p>
                <p className='privacy-text'>Users hereby grant to Nifty10 and its affiliates, partners, licensors and associates a worldwide, irrevocable, royalty-free, non-exclusive, sub-licensable license to use, reproduce, create derivative works of, distribute, publicly perform, publicly display, transfer, transmit, and/or publish Users’ Content for any of the following purposes:</p>
                <ol className="terms-conditions-sub-list roman-sub-list">
                    <li className='privacy-text'>displaying Users’ Content on Nifty10</li>
                    <li className='privacy-text'>distributing Users’ Content, either electronically or via other media, to other Users seeking to download or otherwise acquire it, and/or</li>
                    <li className='privacy-text'>storing Users’ Content in a remote database accessible by end users, for a charge.</li>
                    <li className='privacy-text'>This license shall apply to the distribution and the storage of Users’ Content in any form, medium, or technology.</li>
                </ol>
                <p className='privacy-text'>All names, logos, marks, labels, trademarks, copyrights or intellectual and proprietary rights on the Portal belonging to any person (including User), entity or third party are recognized as proprietary to the respective owners and any claims, controversy or issues against these names, logos, marks, labels, trademarks, copyrights or intellectual and proprietary rights must be directly addressed to the respective parties under notice to Nifty10.</p>
                <li className='terms-conditions-list-item privacy-sub-header'>Taxation</li>
                <p className='privacy-text'>All prizes shall be subject to deduction of tax (“TDS”) as per the Income Tax Act 1961. With effect from 1st April 2023, TDS of 30% shall be deducted on Net Winnings (NW) on each withdrawal request placed by the user.</p>
                <p className='privacy-text'>Net Winnings (‘NW’) shall be calculated as follows: NW = (A+D)-(B+C+E). Where : A= Total withdrawal (including current withdrawal amount), B= Total Deposit, C= Opening Balance at the beginning of financial year, D= Closing balance of the user account at the end of financial year, E= Amount on which TDS was deducted.</p>
                <p className='privacy-text'>In the event, a user does not withdraw any of his winnings during a financial year and has Net Winning balance as at 31 March of each year, then TDS of 30% shall be deducted on such Net Winnings balance from the user’s Winning Account as on 31 March. In case of any revisions by the Government of India to the aforementioned rate or the definition of Net Winnings in the future, TDS will be deducted by Nifty10 in accordance with the then current prescribed TDS rate and the revised definition of Net Winnings. Winners will be provided TDS certificates in respect of such tax deductions. The winners shall be responsible for payment of any other applicable taxes, including but not limited to, income tax, gift tax, etc. in respect of the Net Winnings. Nifty10 shall not in any manner be responsible for users individual tax matters.</p>
                <li className='terms-conditions-list-item privacy-sub-header'>Publicity</li>
                <p className='privacy-text'>Where legal, both Users and winner of Games consent to the use of their name, voice, and likeness/photograph in and in connection with the development, production, distribution and/or exploitation of any Game or the Portal. Winners agree that from the date of notification by Nifty10 of their status as a potential winner and continuing until such time when Nifty10 informs them that they no longer need to do so that they will make themselves available to Nifty10 for publicity, advertising, and promotion activities.</p>
                <li className='terms-conditions-list-item privacy-sub-header'>Release and Limitation of Liability</li>
                <p className='privacy-text'>Users shall access the Nifty10 Services provided on Nifty10 voluntarily and at their own risk. Nifty10 shall, under no circumstances be held responsible or liable on account of any loss or damage sustained (including but not limited to any accident, injury, death, loss of property) by Users or any other person or entity during the course of access to the Nifty10 Services (including participation in the Contest(s)) or as a result of acceptance of any prize.</p>
                <p className='privacy-text'>By entering the contests and accessing the Nifty10 Services provided therein, Users hereby release from and agree to indemnify Nifty10, and/ or any of its directors, employees, partners, associates and licensors, from and against all liability, cost, loss or expense arising out their access to the Nifty10 Services including (but not limited to) personal injury and damage to property and whether direct, indirect, consequential, foreseeable, due to some negligent act or omission on their part, or otherwise.</p>
                <p className='privacy-text'>Nifty10 accepts no liability, whether jointly or severally, for any errors or omissions, whether on behalf of itself or third parties in relation to the prizes.</p>
                <p className='privacy-text'>Users shall be solely responsible for any consequences which may arise due to their access of Nifty10 Services by conducting an illegal act or due to non-conformity with these Terms and Conditions and other rules and regulations in relation to Nifty10 Services, including provision of incorrect address or other personal details. Users also undertake to indemnify Nifty10 and their respective officers, directors, employees and agents on the happening of such an event (including without limitation cost of attorney, legal charges etc.) on full indemnity basis for any loss/damage suffered by Nifty10 on account of such act on the part of the Users.</p>
                <p className='privacy-text'>Users shall indemnify, defend, and hold Nifty10 harmless from any third party/entity/organization claims arising from or related to such User’s engagement with the Nifty10 or participation in any Contest. In no event shall Nifty10 be liable to any User for acts or omissions arising out of or related to User’s engagement with the Nifty10 or his/her participation in any Contest(s).</p>
                <p className='privacy-text'>In consideration of Nifty10 allowing Users to access the Nifty10 Services, to the maximum extent permitted by law, the Users waive and release each and every right or claim, all actions, causes of actions (present or future) each of them has or may have against Nifty10, its respective agents, directors, officers, business associates, group companies, sponsors, employees, or representatives for all and any injuries, accidents, or mishaps (whether known or unknown) or (whether anticipated or unanticipated) arising out of the provision of Nifty10 Services or related to the contests or the prizes of the contests.</p>
                <li className='terms-conditions-list-item privacy-sub-header'>Grievance Redressal Mechanism</li>
                <p className='privacy-text'>In case you have any complaints or grievance pertaining to (i) any User Content that you believe violates these Terms (other than an infringement of Intellectual Property Rights) for the reporting mechanism for such claims, (ii) your access to the Portal or (iii) any User Content which you believe is, prima facie, in the nature of any material which is obscene, defamatory towards the complainant or any person on whose behalf you are making the complaint, or is in the nature of impersonation in an electronic form, including artificially morphed images of such individual, please share the same with us by writing to: grievance@Nifty10.com </p>
                <p className='privacy-text'>In your complaint or grievance, please include the following information:</p>
                <ol className="terms-conditions-sub-list decimal-sub-list">
                    <li className='privacy-text'>Your name and contact details: name, address, contact number and email address</li>
                    <li className='privacy-text'>Your relation to the subject matter of the complaint, i.e. complainant or person acting on behalf of an affected person</li>
                    <li className='privacy-text'>The name and age of the person aggrieved or affected by the subject matter of the complaint, in case your are acting on behalf of such person and a statement, under penalty of perjury, that you are authorized to act on behalf of such person and to provide such person’s personal information to us in relation to the complaint/grievance</li>
                    <li className='privacy-text'>Description of the complaint or grievance with clear identification of the User Content in relation to which such complaint or grievance is made</li>
                    <li className='privacy-text'>A statement that you believe, in good faith, that the User Content violates these Terms</li>
                    <li className='privacy-text'>A statement that the information provided in the complaint or grievance is accurate.</li>
                </ol>
                <p className='privacy-text'>Nifty10 respects the Intellectual Property Rights of others. All names, logos, marks, labels, trademarks, copyrights or intellectual and proprietary rights on the Portal belonging to any person (including User), entity or third party are recognized as proprietary to the respective owners. You are requested to send us a written notice/ intimation if you notice any act of infringement on the Portal, which must include the following information:</p>
                <ol className="terms-conditions-sub-list decimal-sub-list">
                    <li className='privacy-text'>A clear identification of the copyrighted work allegedly infringed</li>
                    <li className='privacy-text'>A clear identification of the allegedly infringing material on the Portal</li>
                    <li className='privacy-text'>Your contact details: name, address, e-mail address and phone number</li>
                    <li className='privacy-text'>A statement that you believe, in good faith, that the use of the copyrighted material allegedly infringed on the Portal is not authorized by your agent or the law</li>
                    <li className='privacy-text'>A statement that the information provided in the notice is accurate, and under penalty of perjury, that the signatory is authorized to act on behalf of the owner of an exclusive copyright right that is allegedly infringed</li>
                    <li className='privacy-text'>Your signature or a signature of your authorized agent.</li>
                    <li className='privacy-text'>The aforesaid notices can be sent to Nifty10 by email at grievance@Nifty10.com</li>
                </ol>
                <p className='privacy-text'>On receiving such complaint, grievance or notice, Nifty10 reserves the right to investigate and/or take such action as the Nifty10 may deem appropriate. The Nifty10 may reach out to you to seek further clarification or assistance with the investigation or verify the statements made in your complaint, grievance or notice, and you acknowledge that your timely assistance with the investigation would facilitate the redressal of the same.</p>
                <p className='privacy-text'>The name and title of the Grievance Redressal Officer is as follows:</p>
                <ol className="terms-conditions-sub-list roman-sub-list">
                    <li className='privacy-text'>Name: P. Nagababu</li>
                    <li className='privacy-text'>Email: grievance@Nifty10.com</li>
                    <li className='privacy-text'>Address: Finpages tech private limited, Unit No.709, Gowra FountainHead, HUDA Techno Enclave, Hyderabad, Telangana – 500081.</li>
                    <li className='privacy-text'>The Grievance Officer identified above pursuant to the provisions of applicable laws including but not limited to the Information Technology Act, 2000 and the Consumer Protection Act, 2019, and the Rules enacted under those laws.</li>
                    <li className='privacy-text'>Nifty10 reserves the right to replace the Grievance Redressal Officer at its discretion through publication of the name and title of such replacement on the website, which replacement shall come into effect immediately upon publication.</li>

                </ol>
                <li className='terms-conditions-list-item privacy-sub-header'>Governing Law, Dispute Resolution and Jurisdiction</li>
                <p className='privacy-text'>These Terms and Conditions shall be governed and construed in accordance with the laws of India.</p>
                <p className='privacy-text'>In the event of any and all disputes arising out of, or in connection with, these Terms and Conditions, the construction, validity, interpretation and enforceability of these Terms and Conditions, or the rights and obligations of the User(s) or Nifty10, the party raising the dispute shall provide a written notification to the other party. On receipt of the written notification, the parties shall first try to resolve the dispute through discussions. In the event that the parties are unable to resolve the dispute within fifteen (15) days of receipt of notification, the dispute shall be settled by arbitration.</p>
                <p className='privacy-text'>The place, venue and seat of arbitration shall be Mumbai, India. All arbitration proceedings shall be conducted in English and by a sole arbitrator in accordance with the provisions of the Arbitration and Conciliation Act, 1996, as amended from time to time.</p>
                <p className='privacy-text'>The arbitration award will be final and binding on the Parties, and each Party will bear its own costs of arbitration and equally share the fees of the arbitrator unless the arbitral tribunal decides otherwise. The arbitrator shall be entitled to pass interim orders and awards, including the orders for specific performance and such orders would be enforceable in competent courts. The arbitrator shall give a reasoned award.</p>
                <p className='privacy-text'>Nothing contained in these Terms and Conditions shall prevent Nifty10 from seeking and obtaining interim or permanent equitable or injunctive relief, or any other relief available to safeguard Nifty10’s interest prior to, during or following the filing of arbitration proceedings or pending the execution of a decision or award in connection with any arbitration proceedings from a court having jurisdiction to grant the same. The pursuit of equitable or injunctive relief shall not constitute a waiver on the part of Nifty10 to pursue any remedy for monetary damages through the arbitration described herein.</p>
                <li className='terms-conditions-list-item privacy-sub-header'>Disclaimers</li>
                <p className='privacy-text'>You agree to hold Nifty10 harmless from any liability such that We cannot be held liable if laws applicable to You restrict or prohibit Your participation in any Game arranged and established through the Portal or otherwise. We make no representations or warranties, implicit or explicit, as to Your legal right to participate in any Game facilitated nor shall any person affiliated, or claiming affiliation with Us, have authority to make such representations or warranties.</p>
                <p className='privacy-text'>Nifty10 is not responsible for: any incorrect, invalid or inaccurate entry information; human errors; postal delays/postage due mail; technical malfunctions; failures, including public utility or telephone outages; omissions, interruptions, deletions or defects of any telephone system or network, computer online systems, data, computer equipment, servers, providers, or software (including, but not limited to software and operating systems that do not permit a User to participate in a Game), including without limitation any injury or damage to any User’s or any other person’s computer or video equipment relating to or resulting from participation in a Game; inability to access the Portal, or any web pages that are part of or related to the Portal; theft, tampering, destruction, or unauthorized access to, or alteration of, entries and/or images of any kind; data that is processed late or incorrectly or is incomplete or lost due to telephone, postal issues, computer or electronic malfunction or traffic congestion on telephone lines or transmission systems, or the Internet, or any service provider’s facilities, or any phone site or website or for any other reason whatsoever; typographical, printing or other errors, or any combination thereof.</p>
                <p className='privacy-text'>The Portal, including, without limitation, all content, software, and functions made available on or accessed through or sent from the Portal, are provided “as is,” “as available,” and “with all faults.” to the fullest extent permissible by law, Nifty10 and its parents, subsidiaries and affiliates make no representation or warranties or endorsements of any kind whatsoever (express or implied) about: (a) the Portal; (b) the content and software on and provided through the Portal; (c) the functions made accessible on or accessed through the Portal; (d) the messages and information sent from the Portal by Users; (e) any products or services offered via the Portal or hypertext links to third parties; and/or (f) security associated with the transmission of sensitive information through the website or any linked site. Nifty10 does not warrant that the Portal, any of the Portal’s functions or any Game contained therein will be uninterrupted or error-free; that defects will be corrected; or that the Portal or the servers that makes them available are free of viruses or other harmful components.</p>
                <p className='privacy-text'>To the extent permitted by law, Nifty10 makes no representations or warranties as to the quality, suitability or merchantability of any prizes and shall not be liable in respect of the same.</p>
                <p className='privacy-text'>Nifty10 does not warrant that your activities or use of the Portal is lawful in any particular jurisdiction and, in any event, the company specifically disclaims such warranties. You understand that by using any of the features of the Portal, you act at your own risk, and you represent and warrant that your activities are lawful in every jurisdiction where you access or use the Portal or the content. Further, Nifty10 and its parents, subsidiaries and affiliates disclaim any express or implied warranties including, without limitation, noninfringement, merchantability, fitness for a particular purpose, and title.</p>
                <p className='privacy-text'>Nifty10, its parents, subsidiaries and affiliates, and the directors, officers, employees, and other representatives of each of them, shall not be liable for the use of the Portal including, without limitation, the content and any errors contained therein.</p>
                <p className='privacy-text'>Any Users sharing any material or information on securities are responsible for their own legal compliance, and you hereby agree that wherever applicable, you have obtained the relevant securities law registrations, including but not limited to registration as an investment adviser, research analyst, or portfolio manager. Nifty10 bears no responsibility and disclaims all liability in this regard for any non-compliance by Users of applicable law. The Portal and its Services are not and are not intended to be a research analyst, portfolio manager or an investment advisor.</p>
                <p className='privacy-text'>We may offer chat features, messaging groups, and other means of social interaction to enable communication between Users. Our role is limited to providing the Services. With respect to User content and communication between Users, our role is that of an ‘intermediary’ as defined under the Information Technology Act, 2000 and the rules thereunder. Being an intermediary, we have no responsibility and / or liability in respect of any User content on the Portal and you are solely responsible therefor. As an ‘intermediary’ under the Information Technology Act, 2000, for the purpose of content posted by Users, we do not pre-screen User content or communications between Users. We have no obligation to monitor any User content apart from our obligations as an ‘intermediary’ under the said Act.</p>
                <p className='privacy-text'>The Portal, Services and any of the content available on the Portal does not and is not intended to provide any investment advice or research analysis with respect to the real life securities market. The content available on the Portal is purely for educational purposes and should not be relied on by the User for the purposes of making any investment in the real life securities market. A User intending to make an investment in the real life securities market should do its own independent due diligence prior to investing.</p>
                <p className='privacy-text'>The Portal, Services and the company entities or individuals do not intend to entice any person to invest in the real life securities market.
                </p>
                <p className='privacy-text'>In consideration of Nifty10 allowing Users to access the Nifty10 Services, to the maximum extent permitted by law, the Users waive and release each and every right or claim, all actions, causes of actions (present or future) each of them has or may have against Nifty10, its respective agents, directors, officers, business associates, group companies, sponsors, employees, or representatives for all and any injuries, accidents, or mishaps (whether known or unknown) or (whether anticipated or unanticipated) arising out of the provision of Nifty10 Services or related to the contests or the prizes of the contests</p>
                <li className='terms-conditions-list-item privacy-sub-header'>Miscellaneous</li>
                <ol className="terms-conditions-sub-list decimal-sub-list">
                    <li className='privacy-text'>The decision of Nifty10 with respect to the awarding of prizes shall be final, binding and non-contestable.</li>
                    <li className='privacy-text'>Nifty10 may, at its sole and absolute discretion, vary or modify the prizes being offered to winners. Participants shall not raise any claim against Nifty10 or question its right to modify such prizes being offered, prior to closure of the Game.</li>
                    <li className='privacy-text'>The Winners shall bear all transaction charges levied for delivery of cash prizes.</li>
                    <li className='privacy-text'>All prizes are non-transferable and non-refundable. Prizes cannot be exchanged / redeemed for cash or kind. No cash claims can be made in lieu of prizes in kind.</li>
                    <li className='privacy-text'>Nifty10 will not bear any responsibility for the transportation or packaging of prizes to the respective winners. Nifty10 shall not be held liable for any loss or damage caused to any           prizes at the time of such transportation. Further, the winners shall bear the shipping, courier or any other delivery cost in respect of the prizes.</li>
                    <li className='privacy-text'>In the event that any provisions of these Terms and Conditions are considered illegal or becomes, or is declared by a court or tribunal of competent jurisdiction to be, invalid, illegal        or  unenforceable, then such provisions shall be stricken from this Agreement and the remainder of this Agreement shall been forced as if such invalid, illegal or unenforceable                clause  or provisions had (to the extent not enforceable) never been contained in these Terms and Conditions. It is hereby clarified that if the illegality has retrospective effect then          such provision(s) will be deemed to be ineffective from its incorporation in these Terms and Conditions.</li>
                </ol>
                <li className='terms-conditions-list-item privacy-sub-header'>Indemnity</li>
                <p className='privacy-text'>By entering into a Game or accepting any prize, all participants, including but not limited to the winner(s), agree to indemnify, release and to hold harmless Nifty10, its parents, subsidiaries, affiliates and agents, as well as the officers, directors, employees, shareholders and representatives of any of the foregoing entities (collectively, the “Released Parties”), from any and all liability, claims or actions of any kind whatsoever, including but not limited to injuries, damages, or losses to persons and property which may be sustained in connection with participation in the Game, the receipt, ownership, use or misuse of any prize or while preparing for, participating in and/or traveling to or from any prize related activity, as well as any claims based on publicity rights, defamation, or invasion of privacy. Nifty10 may, in its sole and absolute discretion, require User to execute a separate release of claims similar to the one listed above in this paragraph as a condition of being awarded any prize or receiving any payout.</p>
                <p className='privacy-text'>Users shall indemnify, defend, and hold Nifty10 harmless from any third party/entity/organization claims arising from or related to such User’s engagement with the Nifty10 or participation in any Game. In no event shall Nifty10 be liable to any User for acts or omissions arising out of or related to User’s engagement with the Nifty10 or his/her participation in any Game(s).</p>
                <p className='privacy-text'>Users shall be solely responsible for any consequences which may arise due to their access of the Portal or Services by conducting an illegal act or due to non-conformity with these Terms and Conditions and other rules and regulations in relation to the Services, including provision of incorrect address or other personal details. Users also undertake to indemnify Nifty10 and their respective officers, directors, employees and agents on the happening of such an event (including without limitation cost of attorney, legal charges etc.) on full indemnity basis for any loss/damage suffered by Nifty10 on account of such act on the part of the Users.</p>
                <li className='terms-conditions-list-item privacy-sub-header'>Prohibited Use of the Portal</li>
                <ul className='privacy-sub-list'>
                    <li className='privacy-sub-list-item'>Illegal Funds</li>
                    <p className='privacy-text'>By accessing the Portal, You declare that the source of funds used by You on the Site is not illegal and that You will not use the Portal or Services in any way as a money transfer system. You will not use the Service for any unlawful activity or prohibited transaction under the laws of any jurisdiction that applies to You. If the Company suspects that You may be engaging in or have engaged in fraudulent, unlawful or improper activity, including without limitation, money laundering activities, Your access to the Service may be suspended or terminated immediately and/or Your User account blocked, and Nifty10 shall be entitled to inform the relevant authorities. You will cooperate fully with the Nifty10 to investigate any suspected unlawful, fraudulent or improper activity.</p>
                    <li className='privacy-sub-list-item'>Collusion</li>
                    <p className='privacy-text'>Collusion occurs when two or more Users attempt to gain an unfair advantage by sharing knowledge or other information to other Users’ disadvantage. Any User who attempts to collude or colludes with any other User while using the Service may be permanently banned from using the Service and their Account may be terminated immediately. Nifty10 will use commercially reasonable efforts to investigate complaints registered against Users suspected of collusion. If Nifty10 is informed during play about suspected collusive behavior, it may, in its sole discretion, terminate suspected Users’ access to the Service, forfeit the winning that accrued due to fraudulent activity and/or block their Accounts. However, under no circumstances shall Nifty10 be liable for any loss, whatsoever, sustained by You as a result of the collusive, or otherwise unlawful activity of any person using the Service and no User shall have the right to require Nifty10 to take any other steps against Users suspected of collusion, cheating or any other form of fraud.</p>
                    <li className='privacy-sub-list-item'>Abuse</li>
                    <p className='privacy-text'>
                        By accessing the Portal, You agree that You will not use any technique to gain an unfair competitive advantage. Such techniques may include, but are not limited to, establishing multiple User accounts or the impersonation of another User or User account.</p>
                </ul>
            </ul>
        </section>
    );
};

export default TermsConditions;
